import { REPO } from './firmware.js'

export const DIAGNOSTIC_COMMANDS = [
  'help',
  'nvs',
  'batt',
  'nodes stats',
  'gps',
  'env',
]

export const CAPTURE_DURATION_MS = 10_000
export const MAX_CAPTURE_CHARS = 48_000

const ISSUE_DIAGNOSTIC_LIMIT = 3_600
const MAX_ISSUE_URL_LENGTH = 7_000

export function redactDiagnostics(value) {
  let text = String(value ?? '')
    .replace(/\x1B\[[0-?]*[ -/]*[@-~]/g, '')
    .replace(/\r\n?/g, '\n')
    .replace(/\0/g, '')

  text = text
    .replace(
      /\b(wifiSsid|wifiPass|ssid|password|passphrase|psk|secret|token|key|channel[_ -]?key|public[_ -]?key|private[_ -]?key|selected)(\s*(?:\[[^\]\n]+\])?\s*[:=]\s*)("[^"\n]*"|'[^'\n]*'|[^\s,\n]+)/gi,
      '$1$2<redacted>'
    )
    .replace(/![0-9a-f]{8}\b/gi, '!<redacted-node>')
    .replace(
      /\b(node(?:Id)?|from|to)(\s*[:=]\s*)(?:!?[0-9a-f]{8}|0x[0-9a-f]+|\d+)\b/gi,
      '$1$2<redacted-node>'
    )
    .replace(/\b(?:[0-9a-f]{2}:){5}[0-9a-f]{2}\b/gi, '<redacted-mac>')
    .replace(/\b(?:\d{1,3}\.){3}\d{1,3}\b/g, '<redacted-ip>')
    .replace(/\b(?:[0-9a-f]{1,4}:){2,7}[0-9a-f]{0,4}\b/gi, '<redacted-ipv6>')
    .replace(
      /(\b(?:lat|latitude|lon|longitude)\s*[:=]\s*)-?\d+(?:\.\d+)?/gi,
      '$1<redacted>'
    )

  return text.trim()
}

export function appendCapture(current, chunk) {
  const next = `${current}${chunk}`
  if (next.length <= MAX_CAPTURE_CHARS) return next

  const headSize = Math.floor(MAX_CAPTURE_CHARS * 0.35)
  const tailSize = MAX_CAPTURE_CHARS - headSize - 64
  return `${next.slice(0, headSize)}\n\n[... serial capture truncated ...]\n\n${next.slice(-tailSize)}`
}

export function compactDiagnostics(value, limit = ISSUE_DIAGNOSTIC_LIMIT) {
  const text = String(value ?? '').trim()
  if (text.length <= limit) return { text, truncated: false }

  const marker = '\n\n[... diagnostics compacted for GitHub URL; use copied full report if needed ...]\n\n'
  const remaining = limit - marker.length
  const headSize = Math.floor(remaining * 0.45)
  const tailSize = remaining - headSize
  return {
    text: `${text.slice(0, headSize)}${marker}${text.slice(-tailSize)}`,
    truncated: true,
  }
}

function reportMetadata({ device, version, capturedAt, userAgent }) {
  return [
    `- Device profile: ${device?.name ?? 'Unknown'} (${device?.env ?? 'unknown'})`,
    `- Website firmware selection: ${version ?? 'Unknown'}`,
    `- Captured: ${capturedAt ?? new Date().toISOString()}`,
    `- Browser: ${String(userAgent || 'Unknown').slice(0, 320)}`,
  ].join('\n')
}

function reportBody({ device, version, summary, diagnostics, capturedAt, userAgent }) {
  const safeSummary = redactDiagnostics(String(summary ?? '')).slice(0, 2_000)
    || 'No problem description provided.'
  const safeDiagnostics = redactDiagnostics(diagnostics)
    .replace(/```/g, '` ` `')

  return [
    '> Generated by the Camillia-MT web flasher. Serial output was automatically redacted and reviewed before submission.',
    '',
    '## What happened',
    '',
    safeSummary,
    '',
    '## Device',
    '',
    reportMetadata({ device, version, capturedAt, userAgent }),
    '',
    '## Serial diagnostics',
    '',
    '```text',
    safeDiagnostics || '[No serial output captured]',
    '```',
  ].join('\n')
}

export function buildDebugReport(options) {
  return reportBody(options)
}

export function buildDebugIssue(options) {
  const redactedDiagnostics = redactDiagnostics(options.diagnostics)
  const issueOptions = {
    ...options,
    summary: redactDiagnostics(String(options.summary ?? '')).slice(0, 600),
    userAgent: String(options.userAgent ?? '').slice(0, 200),
  }
  let diagnosticLimit = ISSUE_DIAGNOSTIC_LIMIT
  let compacted = compactDiagnostics(redactedDiagnostics, diagnosticLimit)
  let body = reportBody({ ...issueOptions, diagnostics: compacted.text })
  const firstLine = issueOptions.summary.trim().split('\n')[0]
  const subject = firstLine || 'Device diagnostics'
  const deviceName = options.device?.name ?? 'Unknown device'
  const title = `[Debug report] ${deviceName}: ${subject}`.slice(0, 160)
  const makeUrl = issueBody => {
    const params = new URLSearchParams({
      assignees: 'oumike',
      title,
      body: issueBody,
    })
    return `https://github.com/${REPO}/issues/new?${params.toString()}`
  }

  let url = makeUrl(body)
  while (url.length > MAX_ISSUE_URL_LENGTH && diagnosticLimit > 400) {
    diagnosticLimit -= 300
    compacted = compactDiagnostics(redactedDiagnostics, diagnosticLimit)
    body = reportBody({ ...issueOptions, diagnostics: compacted.text })
    url = makeUrl(body)
  }
  let diagnosticsOmitted = false
  if (url.length > MAX_ISSUE_URL_LENGTH) {
    diagnosticsOmitted = true
    body = reportBody({
      ...issueOptions,
      summary: issueOptions.summary.slice(0, 240),
      userAgent: '',
      diagnostics: '[Diagnostics omitted from the URL. Use the copied full report.]',
    })
    url = makeUrl(body)
  }

  return {
    url,
    body,
    diagnosticsTruncated: diagnosticsOmitted
      || compacted.truncated
      || diagnosticLimit < ISSUE_DIAGNOSTIC_LIMIT,
  }
}